kind: BuildConfig
apiVersion: v1
metadata:
  name: jenkins-demo-pipeline
  labels:
    app: jenkins-demo-os
spec:
  resources:
    requests:
      cpu: 500Mi
      memory: 500Mi
  source:
    git:
      ref: master
      uri: "https://github.com/lucabarze/jenkins-demo"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
